[package]
name = "rust-audio-plugin"
version = "0.1.0"
edition = "2021"
authors = ["Alex Blease <alexblease@gmail.com>"]


[lib]
crate-type = ["cdylib"]

[dependencies]
nih_plug = { path = "../nih-plug/", features = ["assert_process_allocs"] }

